secretsanta/urls.py
from django.urls import path

from . import views

app_name = "secretsanta"

urlpatterns = [
    path("", views.index, name="index"),
    path("apply/<int:year>/", views.apply, name="apply"),
    path("mark_received/<int:year>/", views.mark_received, name="mark_received"),
    path("pairs/<int:year>/", views.pairs, name="pairs"),
    path("applications/<int:year>/", views.applications, name="applications"),
    path("generate_pairs/<int:year>/", views.queue_generate_pairs, name="generate_pairs"),
    path("notify_santas/<int:year>/", views.queue_notify_santas, name="notify_santas"),
    path("notify_outstanding_santees/<int:year>/", views.queue_notify_outstanding_santees, name="notify_outstanding_santees"),
    path("admin_delete_application/<int:id>/", views.admin_delete_application, name="admin_delete_application"),
]

secretsanta/templates/secretsanta/applications.html
{% extends "secretsanta/base-bs5.html" %}
{% load i18n %}
{% load humanize %}
{% block content %}
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">{% translate "Secret Santa Applications" %}</h3>
        </div>
        <div class="card-body">
            <table class="table table-hover" id="table-secret-santa-applications">
                <thead>
                    <tr>
                        <th class="text-left">{% translate "Application" %}</th>
                        <th class="text-left">{% translate "Affiliation" %}</th>
                        <th class="text-left">{% translate "Manage" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for application in applications %}
                        <tr>
                            <td>{{ application.user.profile.main_character }}</td>
                            <td>{{ application.user.profile.main_character.corporation_name }} / {{ user.profile.main_character.alliance_name|default_if_none:"" }}</td>
                            <td><a class="btn btn-danger" href="{% url 'secretsanta:admin_delete_application' application.id %}" role="button"><span class="fa fas fa-skull-crossbones"></span></a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% if year.open %}
        <a class="btn btn-danger" href="{% url 'secretsanta:generate_pairs' year.year %}" role="button">
            <span class="fa fas fa-skull-crossbones"></span> {% translate "Generate Pairs" %} <span class="fa fas fa-skull-crossbones"></span></a>
    {% endif %}
{% endblock content %}
{% block extra_javascript %}
    {% include "bundles/datatables-js-bs5.html" %}
    {% include "bundles/moment-js.html" %}
{% endblock extra_javascript %}
{% block extra_css %}
    {% include "bundles/datatables-css-bs5.html" %}
{% endblock extra_css %}
{% block extra_script %}
    $(document).ready( function () {
    $('#table-secret-santa-applications').DataTable({
    lengthMenu: [
    [10, 25, 50, 100, -1],
    [10, 25, 50, 100, 'All'],
    ],
    "stateSave": true,
    "stateDuration": 0
    });
    } );
{% endblock extra_script %}

secretsanta/templates/secretsanta/base-bs5.html
{% extends "allianceauth/base-bs5.html" %}
{% load i18n %}
{% load humanize %}
{% load static %}

{% block page_title %}
    {% translate "Secret Santa" %}
{% endblock page_title %}

{% block header_nav_brand %}
    {% translate "Secret Santa" %}
{% endblock header_nav_brand %}

{% block content %}
{% endblock content %}

secretsanta/templates/secretsanta/index.html
{% extends "secretsanta/base-bs5.html" %}
{% load i18n %}
{% load humanize %}
{% block content %}
    <div class="row">
        {% for year in year_renders %}{{ year }}{% endfor %}
    </div>
{% endblock content %}

secretsanta/templates/secretsanta/pairs.html
{% extends "secretsanta/base-bs5.html" %}
{% load i18n %}
{% load humanize %}
{% block content %}
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">{% translate "Secret Santa Pairs" %}</h3>
        </div>
        <div class="card-body">
            <table class="table table-hover" id="table-secret-santa-pairs">
                <thead>
                    <tr>
                        <th class="text-left">{% translate "Santa" %}</th>
                        <th class="text-left">{% translate "Santa Affiliation" %}</th>
                        <th class="text-left">{% translate "Santee" %}</th>
                        <th class="text-left">{% translate "Santee Affiliation" %}</th>
                        <th class="text-left">{% translate "Delivered" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pair in pairs %}
                        <tr>
                            <td>{{ pair.santa.profile.main_character }}</td>
                            <td>{{ pair.santa.profile.main_character.corporation_name }} / {{ pair.santa.profile.main_character.alliance_name|default_if_none:"" }}</td>
                            <td>{{ pair.santee.profile.main_character }}</td>
                            <td>{{ pair.santee.profile.main_character.corporation_name }} / {{ pair.santee.profile.main_character.alliance_name|default_if_none:"" }}</td>
                            <td>{{ pair.delivered }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% if year.open %}
    {% else %}
        <a class="btn btn-warning" href="{% url 'secretsanta:notify_santas' year.year %}" role="button"><span class="fa fas fa-skull-crossbones"></span> {% translate "Notify Santas on Discord" %} <span class="fa fas fa-skull-crossbones"></span></a>
        <a class="btn btn-info" href="{% url 'secretsanta:notify_outstanding_santees' year.year %}" role="button"><span class="fa fas fa-skull-crossbones"></span> {% translate "Remind Outstanding Santas" %} <span class="fa fas fa-skull-crossbones"></span></a>
    {% endif %}
{% endblock content %}
{% block extra_javascript %}
    {% include "bundles/datatables-js-bs5.html" %}
    {% include "bundles/moment-js.html" %}
{% endblock extra_javascript %}
{% block extra_css %}
    {% include "bundles/datatables-css-bs5.html" %}
{% endblock extra_css %}
{% block extra_script %}
    $(document).ready( function () {
    $('#table-secret-santa-pairs').DataTable({
    lengthMenu: [
    [10, 25, 50, 100, -1],
    [10, 25, 50, 100, 'All'],
    ],
    "stateSave": true,
    "stateDuration": 0
    });
    } );
{% endblock extra_script %}

secretsanta/templates/secretsanta/year.html
{% load i18n %}
<div class="col-lg-3">
    {% if year.open %}
        <div class="card text-bg-primary">
            <div class="card-header">{{ year.year }}</div>
            <div class="card-body">
                {% translate "Members" %}: <span class="label label-primary">{{ year.members }}</span>
                <br />
                {% translate "Santee" %}: <span class="label label-primary">{{ users_santee.profile.main_character.character_name }}</span>
                <br />
                <br />
                {% if application_exists %}
                    <span class="btn btn-info" role="button" disabled="disabled">{% translate "Joined" %}</span>
                {% else %}
                    <a class="btn btn-info" href="{% url 'secretsanta:apply' year.year %}" role="button">{% translate "Join" %}</a>
                {% endif %}
                {% if year.participating %}
                    <a class="btn btn-info" href="{% url 'secretsanta:mark_received' year.year %}" role="button">{% translate "Received Gift" %}</a>
                {% endif %}
                {% if perms.secretsanta.manager %}
                    <a class="btn btn-warning" href="{% url 'secretsanta:applications' year.year %}" role="button">{% translate "Applications" %}</a>
                    <a class="btn btn-danger" href="{% url 'secretsanta:pairs' year.year %}" role="button"><span class="fa fas fa-skull-crossbones"></span> {% translate "Administer" %} <span class="fa fas fa-skull-crossbones"></span></a>
                {% endif %}
            </div>
        </div>
    {% else %}
        <div class="card text-bg-secondary">
            <div class="card-header">{{ year.year }}</div>
            <div class="card-body">
                {% translate "Members" %}: <span class="label label-primary">{{ year.members }}</span>
                <br />
                {% translate "Santee" %}: <span class="label label-primary">{{ users_santee }}</span>
                <br />
                <br />
                {% if santapair_exists %}
                    {% if gift_delivered %}
                        <span class="btn btn-info" disabled="disabled" role="button">{% translate "Received Gift" %}</span>
                    {% else %}
                        <a class="btn btn-info" href="{% url 'secretsanta:mark_received' year.year %}" role="button">{% translate "Received Gift" %}</a>
                    {% endif %}
                {% endif %}
                {% if perms.secretsanta.manager %}
                    <a class="btn btn-warning" href="{% url 'secretsanta:applications' year.year %}" role="button">{% translate "Applications" %}</a>
                    <a class="btn btn-danger" href="{% url 'secretsanta:pairs' year.year %}" role="button"><span class="fa fas fa-skull-crossbones"></span> {% translate "Administer" %} <span class="fa fas fa-skull-crossbones"></span></a>
                {% endif %}
            </div>
        </div>
    {% endif %}
</div>